language: java
jdk:
 - oraclejdk8
 - oraclejdk7
 - openjdk7
 - openjdk6
before_install:
 - git clone https://github.com/willp-bl/ProcessIsolatedTika.git
 - cd ProcessIsolatedTika
 - mvn clean install -DskipTests=true
 - cd ..
 - pushd .
 # Get around parent pom issue when building in nanite/ dir
 - mkdir ../webarchive-discovery/ && cd ../webarchive-discovery/
 - git clone https://github.com/ukwa/webarchive-discovery.git
 - cd webarchive-discovery
 - git checkout 1.1.x-bugfix-branch
 - mvn clean install -DskipTests=true -el warc-solr-test-server
 - popd
before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx1024m"
 - "echo $JAVA_OPTS"
 - "ulimit -a"
 - "ulimit -u 2048"
 - "ulimit -a"
 - "umask 022"

