language: java

dist: trusty

jdk:
 - oraclejdk8
 - openjdk8
 - oraclejdk11
 - openjdk11

before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx1024m"
 - "echo $JAVA_OPTS"
 - "ulimit -a"
 - "ulimit -u 2048"
 - "ulimit -a"
 - "umask 022"

